name: Automated Data Preprocessing

on:
  push:
    paths:
      - "online_shoppers_intention_raw.csv"
      - "preprocessing/automate_Abida-Dina-Kamila.py"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run preprocessing automation
        run: |
          python preprocessing/automate_Abida-Dina-Kamila.py

      - name: Verify output
        run: |
          ls -lh preprocessing
          head -n 5 preprocessing/online_shoppers_intention_preprocessing.csv

      - name: Upload preprocessing dataset
        uses: actions/upload-artifact@v4
        with:
          name: online_shoppers_intention_preprocessing
          path: preprocessing/online_shoppers_intention_preprocessing.csv
